import {
  removeCorrectedChatEvents,
  removeCorrectedFamilyEvents,
} from '../src/hooks/useElderChat';
import { extractHealthValues } from '../src/engine/extract';
import { understandElderInput } from '../src/engine/understanding';
import { measurementToEvent, observationToEvent, type HealthEvent } from '../src/pipeline/events';
import type {
  ClaimStatus,
  FamilyHealthEvent,
  HealthMeasurement,
  SymptomTag,
} from '../src/types';

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

const TODAY = '2026-09-10';

function observation(id: string, text: string, tags: SymptomTag[], date = TODAY): HealthEvent {
  return observationToEvent({
    id,
    date,
    source: 'chat',
    text,
    tags,
    visibility: 'private',
  });
}

function measurement(
  id: string,
  metric: HealthMeasurement['metric'],
  value: number,
  sourceText: string,
  date = TODAY,
  source: HealthMeasurement['source'] = 'chat',
): HealthEvent {
  return measurementToEvent({
    id,
    timestamp: `${date}T12:00:00`,
    metric,
    value,
    unit: metric === 'systolic' || metric === 'diastolic' ? 'mmHg' : '%',
    source,
    confidence: 0.9,
    visibility: 'private',
    metadata: { sourceText, extraction: 'rule', eventDate: date },
  });
}

function familyEvent(
  id: string,
  subject: FamilyHealthEvent['subject'],
  text: string,
  tags: SymptomTag[],
  date = TODAY,
  status: ClaimStatus = 'occurred',
  source: FamilyHealthEvent['source'] = 'chat',
): FamilyHealthEvent {
  return {
    id,
    timestamp: `${date}T12:00:00`,
    source,
    subject,
    text,
    tags,
    hasHealthValue: false,
    status,
    visibility: 'private',
    shareMode: 'private',
  };
}

const todayClaim = understandElderInput('我今天头晕', TODAY).claims;
const sameTagEvents: HealthEvent[] = [
  observation('old-dizziness', '我昨天头晕', ['dizziness'], '2026-09-09'),
  observation('latest-dizziness', '我今天头晕', ['dizziness'], TODAY),
];
const correctedSameTagEvents = removeCorrectedChatEvents(sameTagEvents, todayClaim);
assert(
  correctedSameTagEvents.some((event) => event.id === 'old-dizziness'),
  'correcting today dizziness must keep the unrelated yesterday dizziness',
);
assert(
  !correctedSameTagEvents.some((event) => event.id === 'latest-dizziness'),
  'correction must remove the exact latest claim instead of a tag-only match',
);

const multiClaim = understandElderInput('我今天头晕，血压210/125', TODAY).claims;
const bpValues = extractHealthValues('血压210/125');
const multiClaimEvents: HealthEvent[] = [
  observation('multi-dizziness', '我今天头晕', ['dizziness']),
  observation('multi-bp', '血压210/125', ['bpHigh']),
  measurement('multi-sys', 'systolic', 210, '血压210/125'),
  measurement('multi-dia', 'diastolic', 125, '血压210/125'),
  observation('unrelated-future-dizziness', '我今天头晕得轻一点了', ['dizziness']),
  measurement('unrelated-device-bp', 'systolic', 150, '设备读数', TODAY, 'device'),
];
const correctedMultiClaimEvents = removeCorrectedChatEvents(multiClaimEvents, multiClaim);
assert(
  !correctedMultiClaimEvents.some((event) => event.id === 'multi-dizziness'),
  'correction must remove the exact first claim from the corrected turn',
);
assert(
  !correctedMultiClaimEvents.some((event) => event.id === 'multi-bp'),
  'correction must remove the exact BP observation from the corrected turn',
);
assert(
  !correctedMultiClaimEvents.some((event) => event.id === 'multi-sys' || event.id === 'multi-dia'),
  'correction must remove the measurements generated by the corrected BP claim',
);
assert(
  correctedMultiClaimEvents.some((event) => event.id === 'unrelated-future-dizziness'),
  'correction must not use a broad symptom tag to delete a later different observation',
);
assert(
  correctedMultiClaimEvents.some((event) => event.id === 'unrelated-device-bp'),
  'correction must never delete a non-chat measurement',
);
assert(bpValues.length === 2, 'BP fixture must contain both systolic and diastolic values');

const familyClaims = understandElderInput('我爸今天头晕，我妈今天头晕', TODAY).claims;
const familyEvents = [
  familyEvent('father-dizziness', 'father', '我爸今天头晕', ['dizziness']),
  familyEvent('mother-dizziness', 'mother', '我妈今天头晕', ['dizziness']),
  familyEvent('father-other', 'father', '我爸今天头晕得轻一点了', ['dizziness']),
];
const correctedFamilyEvents = removeCorrectedFamilyEvents(familyEvents, familyClaims);
assert(
  !correctedFamilyEvents.some((event) => event.id === 'father-dizziness' || event.id === 'mother-dizziness'),
  'family correction must remove every claim from the corrected previous turn',
);
assert(
  correctedFamilyEvents.some((event) => event.id === 'father-other'),
  'family correction must preserve a different same-tag observation',
);

const uncertainFamilyClaims = understandElderInput('我爸可能头晕', TODAY).claims;
const uncertainFamilyEvents = [
  familyEvent('uncertain-father-dizziness', 'father', '我爸可能头晕', ['dizziness'], TODAY, 'uncertain'),
  familyEvent('uncertain-father-other', 'father', '我爸今天头晕得轻一点了', ['dizziness']),
];
const correctedUncertainFamilyEvents = removeCorrectedFamilyEvents(uncertainFamilyEvents, uncertainFamilyClaims);
assert(
  !correctedUncertainFamilyEvents.some((event) => event.id === 'uncertain-father-dizziness'),
  'correction must remove a previously persisted uncertain family claim',
);
assert(
  correctedUncertainFamilyEvents.some((event) => event.id === 'uncertain-father-other'),
  'uncertain family correction must not remove a different same-tag event',
);

console.log('PASS: claim-scoped correction removes only corrected facts and leaves unrelated evidence intact');
